"""empty message

Revision ID: d80c67ab571d
Revises: ef140893e96f
Create Date: 2019-02-14 21:05:10.659696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80c67ab571d'
down_revision = 'ef140893e96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('uid', sa.String(length=40), nullable=False),
    sa.Column('content', sa.String(length=400), nullable=False),
    sa.Column('salary', sa.String(length=5), nullable=False),
    sa.Column('pmtime', sa.String(length=20), nullable=True),
    sa.Column('smtime', sa.String(length=20), nullable=False),
    sa.Column('sptime', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('task_imgurl', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('re_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
